export const FETCH_POPULAR = 'FETCH_POPULAR';
export const FETCH_UPCOMING = 'FETCH_UPCOMING';
export const FETCH_TOP_RATED = 'FETCH_TOP_RATED';
export const FETCH_KIDS_POPULAR = 'FETCH_KIDS_POPULAR';
export const FETCH_NOW_PLAYING = 'FETCH_NOW_PLAYING';
export const FETCH_SEARCH = 'FETCH_SEARCH';
export const FETCH_MOVIE = 'FETCH_MOVIE';

